### ISSUE TITLE
Create modal for slider

### ISSUE THREAD

**Issue by manuelalonge** [manuelalonge/team-four-webapp#53]
- [x] Pull branch 43 and create new branch
- [x] Add a modal for slider with 1 img only

Time estimate: 0.30
Effective time: 5.20

**Comment by manuelalonge** [comment]
Struggling with modal, I think it is an issue from webpack. Asked for @LucaBert89 support with this to speed up the process.

**Comment by LucaBert89** [comment]
i solved the problem modifying the webpack config file. Now you can see the images again
